[package]
name = "homework-11"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ['derive'] }
derive_builder = "0.20.2"
plotters = "0.3.7"
rand = "0.9.2"
rand_distr = "0.5.1"
